
[book]

format = "HTML" # other option is "EPUB"

input_filename  = "./unzip/arthur-conan-doyle_a-study-in-scarlet/epub/toc.xhtml"
output_filename = "./out/arthur-conan-doyle_a-study-in-scarlet/epub/toc.xhtml"

words_filename = "./configuration/arthur-conan-doyle_a-study-in-scarlet/words.json"

phrases_filename = "./configuration/arthur-conan-doyle_a-study-in-scarlet/phrases.txt"
